"""Include country

Revision ID: b33947c8cb6d
Revises: c22418ab1f29
Create Date: 2023-10-28 07:29:41.293930

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b33947c8cb6d'
down_revision: Union[str, None] = 'c22418ab1f29'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipes', sa.Column('country', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recipes', 'country')
    # ### end Alembic commands ###
